import React from 'react';
import { Link } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { 
  Sparkles, 
  ArrowRight, 
  BrainCircuit, 
  TrendingUp, 
  ShieldCheck, 
  Zap, 
  Compass, 
  GraduationCap 
} from 'lucide-react';

const LandingPage = () => {
  const { user } = useApp();

  const features = [
    {
      icon: BrainCircuit,
      title: 'AI Learning Pathmaker',
      description: 'Generate customizable step-by-step roadmaps based on your target career track and skill levels.',
      color: 'indigo'
    },
    {
      icon: TrendingUp,
      title: 'Real-Time Skill Profiler',
      description: 'Track module completions and watch your skill scores adjust dynamically as you progress.',
      color: 'emerald'
    },
    {
      icon: Compass,
      title: 'Smart Activity Recommender',
      description: 'Get immediate next-step activities generated by the AI agent based on historical completion logs.',
      color: 'purple'
    },
    {
      icon: ShieldCheck,
      title: 'Admin Control Console',
      description: 'Easy-to-use manager tools for creating, updating, and removing courses and tracking enrollment counts.',
      color: 'rose'
    }
  ];

  const colorMap = {
    indigo: 'bg-indigo-500/10 text-indigo-600 dark:bg-indigo-400/20 dark:text-indigo-400',
    emerald: 'bg-emerald-500/10 text-emerald-600 dark:bg-emerald-400/20 dark:text-emerald-400',
    purple: 'bg-purple-500/10 text-purple-650 dark:bg-purple-400/20 dark:text-purple-400',
    rose: 'bg-rose-500/10 text-rose-600 dark:bg-rose-400/20 dark:text-rose-400'
  };

  return (
    <div className="relative min-h-[calc(100vh-4rem)] overflow-hidden bg-slate-50 dark:bg-slate-900 transition-colors">
      {/* Decorative Blur Spheres */}
      <div className="absolute top-1/4 left-1/10 h-72 w-72 rounded-full bg-indigo-500/10 blur-3xl dark:bg-indigo-500/5"></div>
      <div className="absolute bottom-1/4 right-1/10 h-80 w-80 rounded-full bg-purple-500/10 blur-3xl dark:bg-purple-500/5"></div>

      <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24 relative z-10">
        {/* Hero Banner */}
        <div className="text-center">
          <div className="mx-auto flex max-w-fit items-center gap-2 rounded-full border border-indigo-200/50 bg-indigo-50/50 px-4 py-1.5 text-xs font-semibold text-indigo-700 dark:border-indigo-900/40 dark:bg-indigo-950/20 dark:text-indigo-400 animate-pulse">
            <Sparkles className="h-4 w-4" />
            <span>AI-Powered LMS Engine is Live!</span>
          </div>

          <h1 className="mt-8 text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl md:text-6xl dark:text-white leading-[1.15]">
            Supercharge Your Skills with <br className="hidden sm:inline" />
            <span className="bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-500 bg-clip-text text-transparent dark:from-indigo-400 dark:via-purple-400 dark:to-pink-400">
              AI-Guided Learning Roadmaps
            </span>
          </h1>

          <p className="mx-auto mt-6 max-w-2xl text-base sm:text-lg text-slate-500 dark:text-slate-400 font-medium leading-relaxed">
            Choose your career goal, select your skill level, and let our intelligent engine generate a customizable roadmap of modules, visual analytics, and immediate next activities.
          </p>

          <div className="mt-10 flex flex-wrap justify-center gap-4">
            {user ? (
              <Link
                to={user.role === 'admin' ? '/admin' : '/dashboard'}
                className="flex items-center gap-2 rounded-xl bg-indigo-600 px-6 py-3.5 text-sm font-extrabold text-white shadow-lg shadow-indigo-650/20 transition-all hover:bg-indigo-500 hover:shadow-indigo-500/30 active:scale-[0.98]"
              >
                <span>Go to Dashboard</span>
                <ArrowRight className="h-4 w-4" />
              </Link>
            ) : (
              <>
                <Link
                  to="/register"
                  className="flex items-center gap-2 rounded-xl bg-indigo-600 px-6 py-3.5 text-sm font-extrabold text-white shadow-lg shadow-indigo-650/20 transition-all hover:bg-indigo-500 hover:shadow-indigo-500/30 active:scale-[0.98]"
                >
                  <span>Get Started for Free</span>
                  <ArrowRight className="h-4 w-4" />
                </Link>
                <Link
                  to="/login"
                  className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-extrabold text-slate-700 hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300 dark:hover:bg-slate-900"
                >
                  <span>Explore Tracks</span>
                </Link>
              </>
            )}
          </div>
        </div>

        {/* Feature Grid Section */}
        <div className="mt-24">
          <div className="text-center">
            <h2 className="text-2xl font-extrabold text-slate-950 dark:text-white sm:text-3xl">
              Engineered for Professional Education
            </h2>
            <p className="mt-4 text-sm font-semibold text-slate-400">
              Everything you need to master tech stacks and track career milestones in one place.
            </p>
          </div>

          <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {features.map((feat, idx) => {
              const Icon = feat.icon;
              return (
                <div 
                  key={idx} 
                  className="group rounded-2xl border border-slate-200/50 bg-white p-6 shadow-sm transition-all duration-300 hover:shadow-md dark:border-slate-800/50 dark:bg-slate-950"
                >
                  <div className={`flex h-11 w-11 items-center justify-center rounded-xl ${colorMap[feat.color]}`}>
                    <Icon className="h-5 w-5" />
                  </div>
                  <h3 className="mt-5 text-base font-bold text-slate-950 dark:text-white group-hover:text-indigo-650 dark:group-hover:text-indigo-400 transition-colors">
                    {feat.title}
                  </h3>
                  <p className="mt-2.5 text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                    {feat.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>

        {/* Highlight Banner */}
        <div className="mt-24 rounded-3xl bg-gradient-to-r from-indigo-600 to-purple-600 p-8 sm:p-12 text-center text-white relative overflow-hidden shadow-xl shadow-indigo-650/15">
          <div className="absolute top-0 right-0 -mt-10 -mr-10 h-40 w-40 rounded-full bg-white/5 blur-xl"></div>
          <div className="relative z-10 mx-auto max-w-2xl">
            <GraduationCap className="mx-auto h-12 w-12 text-indigo-200" />
            <h2 className="mt-6 text-3xl font-extrabold tracking-tight sm:text-4xl">
              Ready to construct your career roadmap?
            </h2>
            <p className="mt-4 text-sm text-indigo-100 font-semibold leading-relaxed">
              Create a free account, select an engineering path, and let the AI compile your study sequence.
            </p>
            <div className="mt-8 flex justify-center">
              <Link
                to={user ? '/dashboard' : '/register'}
                className="flex items-center gap-2 rounded-xl bg-white px-6 py-3 text-sm font-extrabold text-indigo-600 transition-all hover:bg-slate-50 active:scale-[0.98]"
              >
                <span>Launch Your Pathway</span>
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LandingPage;
